language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd backend/frontend/
  - nvm install 5.0
  - nvm use 5.0
  - npm install
  - npm install mocha -g
  - cd ../..

# command to run tests
before_script:
  - cd backend/
  - mkdir -p db/
  - sqlite3 db/course-dashboard.db < schema.sql
script:
  - python cdApp.py & sleep 1
  - python testCRUD.py
  - cd frontend/
  - npm test
  - cd ..
  - sqlite3 db/course-dashboard.db < schema.sql
  - python cdApp.py & sleep 1
  - cd frontend/
  - mocha selenium-test.js --compilers js:babel-core/register --timeout 10000
after_script: kill -- -$!
