language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
  - cd backend/
script:
  - sqlite2 "db/course-dashboard.db" < schema.sql
  - python cdApp.py &
  - sleep 1
  - python testCRUD.py
after_script: killall setup.sh
