language: python
sudo: false
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - cd backend/frontend/
  - nvm install node # latest stable node version
  - npm install
  - cd ../..

# command to run tests
before_script:
  - cd backend/
  - mkdir -p db/
  - sqlite3 db/course-dashboard.db < schema.sql
script:
  - python cdApp.py & sleep 1
  - python testCRUD.py
  - cd frontend/
  - npm test
