language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
beforescript:
  - cd backend/
  - ./setup.sh &>/dev/null &
script: python testCRUD.py
afterscript: killall setup.sh
